// Animations List
// animList.sqf
//Animation, type, not used?, name, uses weapon, script
ANIM_AllAnimationArray = [
    ["AmovPercMstpSnonWnonDnon_AmovPercMstpSsurWnonDnon", "handsup", "anim", localize "STRS_anim_var_handsup", 2, ""],
	["normal", "normal", "anim", localize "STRS_anim_var_normal", 2, ""],
	["holsterrifle", "holsterrifle", "special",	localize "STRS_anim_var_holsterrifle", 2, "holster.sqf"],
	["holsterpistol", "holsterpistol", "special", localize "STRS_anim_var_holsterpistol", 2, "holster.sqf"],
    ["AmovPercMstpSlowWrflDnon_ActsPercMstpSlowWrflDr_HideFromFire", "step_right", "anim", "Step Right", 1, ""],
    ["ActsPercMrunSlowWrflDf_FlipFlopPara", "combat_roll", "anim", "Combat roll", 1, ""],
    ["ActsPercMstpSnonWpstDnon_sceneBardakRifle01", "rifle_scene1", "anim", "Rifle Scene", 1, ""],
    ["ActsPercMstpSnonWpstDnon_sceneBardakPistol01", "pistol_scene1", "anim", "Pistol Scene", 1, ""],
    ["AmelPercMstpSlowWrflDnon_StrokeGun", "rifle_hit", "anim", "Hit with rifle", 1, ""],
    ["ActsPercMstpSnonWpstDnon_suicide1B", "suicide", "anim", "Suicide", 1, ""],
    ["AidlPpneMstpSnonWnonDnon_SleepA_death", "lay_back1", "anim", "Lay on back", 0, ""],
    ["AidlPercSnonWnonDnon_talk1", "talk1", "anim", "Talk (1)", 0, ""],
    ["c7a_bravo_dovadeni5", "cheer1", "anim", "Cheer (1)", 0, ""],
    ["c7a_bravo_dovadeni4", "cheer2", "anim", "Cheer (2)", 0, ""],
    ["c7a_bravo_dovadeni3", "cheer3", "anim", "Cheer (3)", 0, ""],
    ["c7a_bravoTleskani_idle1", "clapping", "anim", "Clapping", 0, ""],
    ["ActsPercSnonWnonDnon_assembling", "assembly", "anim", "Assembly", 0, ""],
   	["ActsPercSnonWnonDnon_carFixing", "fixCar1", "anim", "Fix Vehicle (1)", 0, ""],
    ["ActsPercSnonWnonDnon_carFixing2", "fixCar2", "anim", "Fix Vehicle (2)", 0, ""],
    ["ActsPercMstpSnonWnonDnon_DancingDuoIvan", "dance1", "anim", "Dance (1)", 0, ""],
    ["ActsPercMstpSnonWnonDnon_DancingDuoStefan", "dance2", "anim", "Dance (2)", 0, ""],
    ["ActsPercMstpSnonWnonDnon_DancingStefan", "dance3", "anim", "Dance (3)", 0, ""],
    ["NavigationDriverReverse", "nav1", "anim", "Navigate Vehicle", 0, ""],
    ["NavigationHeli", "nav2", "anim", "Navigate Helicopter", 0, ""],
    ["RepairingKneel", "rep1", "anim", "Repair Vehicle (Kneel)", 0, ""],
    ["RepairingErc", "wash1", "anim", "Wash Vehicle", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle56kliky", "full_workout", "anim", "Do Full workout", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle68boxing", "boxing", "anim", "Boxing", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle69drepy", "knee_bends", "anim", "Do Knee Bends", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle70chozeniPoRukou", "hand_stands", "anim", "Do Hand Stands", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle71kliky", "push_ups", "anim", "Do Pushups", 0, ""],
    ["AmovPercMstpSnonWnonDnon_idle72lehSedy", "sit_ups", "anim", "Do Situps", 0, ""],
    ["AmovPercMstpSnonWnonDnon_exerciseKata", "karate", "anim", "Do Karate", 0, ""],
    ["amovpsitmstpsraswrfldnon_smoking", "smoking", "anim", "Sit Smoking", 0, ""],
    ["amovpsitmstpsraswrfldnon_weaponcheck1", "sit_weapon", "anim", "Sit Checking Weapon", 0, ""],
    ["CtsDoktor_Vojak_hulakani1", "idle_rifle", "anim", "Idle (Rifle)", 0, ""]
];
